tasks:
  - name: Run the stack
    init: |
      echo 'TODO: build project'
    command: |
      sed -i 's/$BACKADD/'"5000-${GITPOD_WORKSPACE_URL##https://}"'/' Instruction.txt && gp open Instruction.txt && docker-compose up 
ports:
  - port: 5000
    visibility: public
